# Configuración de MongoDB
spring.data.mongodb.uri=${uri-connection}

# Configuración de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/financial_management_db
spring.datasource.username=postgres
spring.datasource.password=postgresql134

# Configuración de JPA para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Perfil activo
spring.profiles.active=postgres


security.jwt.secret-key=Q29udHJhc2XDsWFfc3VwZXJzZWNyZXRhX3BhaXpfMjAyMjEzNA==
# 3h in millisecond
security.jwt.expiration-time=10800000


spring.main.allow-circular-references=true